[project]
name = "hubspot-wefact"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "hubspot-api-client==12.0.0",
    "pydantic>=2.10.6",
    "requests>=2.32.5",
    "simplejson>=3.20.2",
]
